// Generated by gencpp from file tiago1/ArmControlFeedback.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_ARMCONTROLFEEDBACK_H
#define TIAGO1_MESSAGE_ARMCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago1
{
template <class ContainerAllocator>
struct ArmControlFeedback_
{
  typedef ArmControlFeedback_<ContainerAllocator> Type;

  ArmControlFeedback_()
    : positions()
    , velocities()
    , efforts()  {
    }
  ArmControlFeedback_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , velocities(_alloc)
    , efforts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _positions_type;
  _positions_type positions;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocities_type;
  _velocities_type velocities;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _efforts_type;
  _efforts_type efforts;





  typedef boost::shared_ptr< ::tiago1::ArmControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago1::ArmControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ArmControlFeedback_

typedef ::tiago1::ArmControlFeedback_<std::allocator<void> > ArmControlFeedback;

typedef boost::shared_ptr< ::tiago1::ArmControlFeedback > ArmControlFeedbackPtr;
typedef boost::shared_ptr< ::tiago1::ArmControlFeedback const> ArmControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago1::ArmControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago1::ArmControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago1::ArmControlFeedback_<ContainerAllocator1> & lhs, const ::tiago1::ArmControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions &&
    lhs.velocities == rhs.velocities &&
    lhs.efforts == rhs.efforts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago1::ArmControlFeedback_<ContainerAllocator1> & lhs, const ::tiago1::ArmControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago1::ArmControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::ArmControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::ArmControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9ca0af36daadfa3b4628ccba7ca6819";
  }

  static const char* value(const ::tiago1::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9ca0af36daadfa3ULL;
  static const uint64_t static_value2 = 0xb4628ccba7ca6819ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago1/ArmControlFeedback";
  }

  static const char* value(const ::tiago1::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] efforts\n"
"\n"
;
  }

  static const char* value(const ::tiago1::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.velocities);
      stream.next(m.efforts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago1::ArmControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago1::ArmControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "efforts[]" << std::endl;
    for (size_t i = 0; i < v.efforts.size(); ++i)
    {
      s << indent << "  efforts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.efforts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO1_MESSAGE_ARMCONTROLFEEDBACK_H
