// Generated by gencpp from file tiago1/GripperControlGoal.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_GRIPPERCONTROLGOAL_H
#define TIAGO1_MESSAGE_GRIPPERCONTROLGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago1
{
template <class ContainerAllocator>
struct GripperControlGoal_
{
  typedef GripperControlGoal_<ContainerAllocator> Type;

  GripperControlGoal_()
    : gripnogrip(false)  {
    }
  GripperControlGoal_(const ContainerAllocator& _alloc)
    : gripnogrip(false)  {
  (void)_alloc;
    }



   typedef uint8_t _gripnogrip_type;
  _gripnogrip_type gripnogrip;





  typedef boost::shared_ptr< ::tiago1::GripperControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago1::GripperControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlGoal_

typedef ::tiago1::GripperControlGoal_<std::allocator<void> > GripperControlGoal;

typedef boost::shared_ptr< ::tiago1::GripperControlGoal > GripperControlGoalPtr;
typedef boost::shared_ptr< ::tiago1::GripperControlGoal const> GripperControlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago1::GripperControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago1::GripperControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago1::GripperControlGoal_<ContainerAllocator1> & lhs, const ::tiago1::GripperControlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.gripnogrip == rhs.gripnogrip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago1::GripperControlGoal_<ContainerAllocator1> & lhs, const ::tiago1::GripperControlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tiago1::GripperControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago1::GripperControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::GripperControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::GripperControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::GripperControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::GripperControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago1::GripperControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf3148cf31b5505879c305233af44a4";
  }

  static const char* value(const ::tiago1::GripperControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf3148cf31b5505ULL;
  static const uint64_t static_value2 = 0x879c305233af44a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago1::GripperControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago1/GripperControlGoal";
  }

  static const char* value(const ::tiago1::GripperControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago1::GripperControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"bool gripnogrip\n"
;
  }

  static const char* value(const ::tiago1::GripperControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago1::GripperControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripnogrip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago1::GripperControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago1::GripperControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "gripnogrip: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripnogrip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO1_MESSAGE_GRIPPERCONTROLGOAL_H
