// Generated by gencpp from file tiago1/robotstatedecision.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_ROBOTSTATEDECISION_H
#define TIAGO1_MESSAGE_ROBOTSTATEDECISION_H

#include <ros/service_traits.h>


#include <tiago1/robotstatedecisionRequest.h>
#include <tiago1/robotstatedecisionResponse.h>


namespace tiago1
{

struct robotstatedecision
{

typedef robotstatedecisionRequest Request;
typedef robotstatedecisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotstatedecision
} // namespace tiago1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago1::robotstatedecision > {
  static const char* value()
  {
    return "33ec071b72a9a044f86da64824d0e481";
  }

  static const char* value(const ::tiago1::robotstatedecision&) { return value(); }
};

template<>
struct DataType< ::tiago1::robotstatedecision > {
  static const char* value()
  {
    return "tiago1/robotstatedecision";
  }

  static const char* value(const ::tiago1::robotstatedecision&) { return value(); }
};


// service_traits::MD5Sum< ::tiago1::robotstatedecisionRequest> should match
// service_traits::MD5Sum< ::tiago1::robotstatedecision >
template<>
struct MD5Sum< ::tiago1::robotstatedecisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago1::robotstatedecision >::value();
  }
  static const char* value(const ::tiago1::robotstatedecisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago1::robotstatedecisionRequest> should match
// service_traits::DataType< ::tiago1::robotstatedecision >
template<>
struct DataType< ::tiago1::robotstatedecisionRequest>
{
  static const char* value()
  {
    return DataType< ::tiago1::robotstatedecision >::value();
  }
  static const char* value(const ::tiago1::robotstatedecisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago1::robotstatedecisionResponse> should match
// service_traits::MD5Sum< ::tiago1::robotstatedecision >
template<>
struct MD5Sum< ::tiago1::robotstatedecisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago1::robotstatedecision >::value();
  }
  static const char* value(const ::tiago1::robotstatedecisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago1::robotstatedecisionResponse> should match
// service_traits::DataType< ::tiago1::robotstatedecision >
template<>
struct DataType< ::tiago1::robotstatedecisionResponse>
{
  static const char* value()
  {
    return DataType< ::tiago1::robotstatedecision >::value();
  }
  static const char* value(const ::tiago1::robotstatedecisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO1_MESSAGE_ROBOTSTATEDECISION_H
