// Generated by gencpp from file tiago1/robotstatedecisionRequest.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_ROBOTSTATEDECISIONREQUEST_H
#define TIAGO1_MESSAGE_ROBOTSTATEDECISIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago1
{
template <class ContainerAllocator>
struct robotstatedecisionRequest_
{
  typedef robotstatedecisionRequest_<ContainerAllocator> Type;

  robotstatedecisionRequest_()
    : state_input()  {
    }
  robotstatedecisionRequest_(const ContainerAllocator& _alloc)
    : state_input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_input_type;
  _state_input_type state_input;





  typedef boost::shared_ptr< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robotstatedecisionRequest_

typedef ::tiago1::robotstatedecisionRequest_<std::allocator<void> > robotstatedecisionRequest;

typedef boost::shared_ptr< ::tiago1::robotstatedecisionRequest > robotstatedecisionRequestPtr;
typedef boost::shared_ptr< ::tiago1::robotstatedecisionRequest const> robotstatedecisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago1::robotstatedecisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago1::robotstatedecisionRequest_<ContainerAllocator1> & lhs, const ::tiago1::robotstatedecisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state_input == rhs.state_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago1::robotstatedecisionRequest_<ContainerAllocator1> & lhs, const ::tiago1::robotstatedecisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88ec6b5132252a36d6685298a06667f7";
  }

  static const char* value(const ::tiago1::robotstatedecisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88ec6b5132252a36ULL;
  static const uint64_t static_value2 = 0xd6685298a06667f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago1/robotstatedecisionRequest";
  }

  static const char* value(const ::tiago1::robotstatedecisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state_input \n"
;
  }

  static const char* value(const ::tiago1::robotstatedecisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotstatedecisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago1::robotstatedecisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago1::robotstatedecisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "state_input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO1_MESSAGE_ROBOTSTATEDECISIONREQUEST_H
