// Generated by gencpp from file tiago1/robotstatedecisionResponse.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_ROBOTSTATEDECISIONRESPONSE_H
#define TIAGO1_MESSAGE_ROBOTSTATEDECISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago1
{
template <class ContainerAllocator>
struct robotstatedecisionResponse_
{
  typedef robotstatedecisionResponse_<ContainerAllocator> Type;

  robotstatedecisionResponse_()
    : state_output()
    , id_client(0)
    , order()
    , success(false)  {
    }
  robotstatedecisionResponse_(const ContainerAllocator& _alloc)
    : state_output(_alloc)
    , id_client(0)
    , order(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_output_type;
  _state_output_type state_output;

   typedef int32_t _id_client_type;
  _id_client_type id_client;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _order_type;
  _order_type order;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotstatedecisionResponse_

typedef ::tiago1::robotstatedecisionResponse_<std::allocator<void> > robotstatedecisionResponse;

typedef boost::shared_ptr< ::tiago1::robotstatedecisionResponse > robotstatedecisionResponsePtr;
typedef boost::shared_ptr< ::tiago1::robotstatedecisionResponse const> robotstatedecisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago1::robotstatedecisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago1::robotstatedecisionResponse_<ContainerAllocator1> & lhs, const ::tiago1::robotstatedecisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state_output == rhs.state_output &&
    lhs.id_client == rhs.id_client &&
    lhs.order == rhs.order &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago1::robotstatedecisionResponse_<ContainerAllocator1> & lhs, const ::tiago1::robotstatedecisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52bb16fdddb35bef99f76c3abb84b931";
  }

  static const char* value(const ::tiago1::robotstatedecisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52bb16fdddb35befULL;
  static const uint64_t static_value2 = 0x99f76c3abb84b931ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago1/robotstatedecisionResponse";
  }

  static const char* value(const ::tiago1::robotstatedecisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state_output\n"
"int32 id_client\n"
"string[] order\n"
"bool success\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::tiago1::robotstatedecisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_output);
      stream.next(m.id_client);
      stream.next(m.order);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotstatedecisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago1::robotstatedecisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago1::robotstatedecisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "state_output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state_output);
    s << indent << "id_client: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id_client);
    s << indent << "order[]" << std::endl;
    for (size_t i = 0; i < v.order.size(); ++i)
    {
      s << indent << "  order[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO1_MESSAGE_ROBOTSTATEDECISIONRESPONSE_H
