// Generated by gencpp from file tiago1/send_order.msg
// DO NOT EDIT!


#ifndef TIAGO1_MESSAGE_SEND_ORDER_H
#define TIAGO1_MESSAGE_SEND_ORDER_H

#include <ros/service_traits.h>


#include <tiago1/send_orderRequest.h>
#include <tiago1/send_orderResponse.h>


namespace tiago1
{

struct send_order
{

typedef send_orderRequest Request;
typedef send_orderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_order
} // namespace tiago1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago1::send_order > {
  static const char* value()
  {
    return "54d692335fd48f1476d58fcf2615595d";
  }

  static const char* value(const ::tiago1::send_order&) { return value(); }
};

template<>
struct DataType< ::tiago1::send_order > {
  static const char* value()
  {
    return "tiago1/send_order";
  }

  static const char* value(const ::tiago1::send_order&) { return value(); }
};


// service_traits::MD5Sum< ::tiago1::send_orderRequest> should match
// service_traits::MD5Sum< ::tiago1::send_order >
template<>
struct MD5Sum< ::tiago1::send_orderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago1::send_order >::value();
  }
  static const char* value(const ::tiago1::send_orderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago1::send_orderRequest> should match
// service_traits::DataType< ::tiago1::send_order >
template<>
struct DataType< ::tiago1::send_orderRequest>
{
  static const char* value()
  {
    return DataType< ::tiago1::send_order >::value();
  }
  static const char* value(const ::tiago1::send_orderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago1::send_orderResponse> should match
// service_traits::MD5Sum< ::tiago1::send_order >
template<>
struct MD5Sum< ::tiago1::send_orderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago1::send_order >::value();
  }
  static const char* value(const ::tiago1::send_orderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago1::send_orderResponse> should match
// service_traits::DataType< ::tiago1::send_order >
template<>
struct DataType< ::tiago1::send_orderResponse>
{
  static const char* value()
  {
    return DataType< ::tiago1::send_order >::value();
  }
  static const char* value(const ::tiago1::send_orderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO1_MESSAGE_SEND_ORDER_H
