// Auto-generated. Do not edit!

// (in-package tiago1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GripperControlGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.gripnogrip = null;
    }
    else {
      if (initObj.hasOwnProperty('gripnogrip')) {
        this.gripnogrip = initObj.gripnogrip
      }
      else {
        this.gripnogrip = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GripperControlGoal
    // Serialize message field [gripnogrip]
    bufferOffset = _serializer.bool(obj.gripnogrip, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GripperControlGoal
    let len;
    let data = new GripperControlGoal(null);
    // Deserialize message field [gripnogrip]
    data.gripnogrip = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tiago1/GripperControlGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2cf3148cf31b5505879c305233af44a4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    bool gripnogrip
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GripperControlGoal(null);
    if (msg.gripnogrip !== undefined) {
      resolved.gripnogrip = msg.gripnogrip;
    }
    else {
      resolved.gripnogrip = false
    }

    return resolved;
    }
};

module.exports = GripperControlGoal;
