<<<<<<< HEAD
set(tiago1_MESSAGE_FILES "/root/cogar_ws/devel/share/tiago1/msg/MovementControlAction.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionResult.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlResult.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlAction.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionResult.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlResult.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlAction.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlActionGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlActionResult.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlActionFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlResult.msg;/root/cogar_ws/devel/share/tiago1/msg/GripperControlFeedback.msg")
=======
<<<<<<< HEAD
set(tiago1_MESSAGE_FILES "/root/Desktop/cogar_ass1/cogar_ws/src/tiago1/msg/Voice_rec.msg")
=======
set(tiago1_MESSAGE_FILES "/root/cogar_ws/devel/share/tiago1/msg/MovementControlAction.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionResult.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlActionFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlResult.msg;/root/cogar_ws/devel/share/tiago1/msg/MovementControlFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlAction.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionResult.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlActionFeedback.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlGoal.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlResult.msg;/root/cogar_ws/devel/share/tiago1/msg/ArmControlFeedback.msg")
>>>>>>> 12be1fcab963b329af0649c4075d9d1835a9ee03
>>>>>>> aca6529c9f600548f857dc744acf75bc94567623
set(tiago1_SERVICE_FILES "")
