(cl:defpackage tiago1-srv
  (:use )
  (:export
   "GETNEXTID"
   "<GETNEXTID-REQUEST>"
   "GETNEXTID-REQUEST"
   "<GETNEXTID-RESPONSE>"
   "GETNEXTID-RESPONSE"
   "ROBOTSTATEDECISION"
   "<ROBOTSTATEDECISION-REQUEST>"
   "ROBOTSTATEDECISION-REQUEST"
   "<ROBOTSTATEDECISION-RESPONSE>"
   "ROBOTSTATEDECISION-RESPONSE"
   "SEND_ORDER"
   "<SEND_ORDER-REQUEST>"
   "SEND_ORDER-REQUEST"
   "<SEND_ORDER-RESPONSE>"
   "SEND_ORDER-RESPONSE"
  ))

