(cl:defpackage tiago1-msg
  (:use )
  (:export
   "<MOVEMENTCONTROLACTION>"
   "MOVEMENTCONTROLACTION"
   "<MOVEMENTCONTROLACTIONFEEDBACK>"
   "MOVEMENTCONTROLACTIONFEEDBACK"
   "<MOVEMENTCONTROLACTIONGOAL>"
   "MOVEMENTCONTROLACTIONGOAL"
   "<MOVEMENTCONTROLACTIONRESULT>"
   "MOVEMENTCONTROLACTIONRESULT"
   "<MOVEMENTCONTROLFEEDBACK>"
   "MOVEMENTCONTROLFEEDBACK"
   "<MOVEMENTCONTROLGOAL>"
   "MOVEMENTCONTROLGOAL"
   "<MOVEMENTCONTROLRESULT>"
   "MOVEMENTCONTROLRESULT"
  ))

