(cl:defpackage tiago1-msg
  (:use )
  (:export
<<<<<<< HEAD
   "<VOICE_REC>"
   "VOICE_REC"
=======
   "<ARMCONTROLACTION>"
   "ARMCONTROLACTION"
   "<ARMCONTROLACTIONFEEDBACK>"
   "ARMCONTROLACTIONFEEDBACK"
   "<ARMCONTROLACTIONGOAL>"
   "ARMCONTROLACTIONGOAL"
   "<ARMCONTROLACTIONRESULT>"
   "ARMCONTROLACTIONRESULT"
   "<ARMCONTROLFEEDBACK>"
   "ARMCONTROLFEEDBACK"
   "<ARMCONTROLGOAL>"
   "ARMCONTROLGOAL"
   "<ARMCONTROLRESULT>"
   "ARMCONTROLRESULT"
   "<MOVEMENTCONTROLACTION>"
   "MOVEMENTCONTROLACTION"
   "<MOVEMENTCONTROLACTIONFEEDBACK>"
   "MOVEMENTCONTROLACTIONFEEDBACK"
   "<MOVEMENTCONTROLACTIONGOAL>"
   "MOVEMENTCONTROLACTIONGOAL"
   "<MOVEMENTCONTROLACTIONRESULT>"
   "MOVEMENTCONTROLACTIONRESULT"
   "<MOVEMENTCONTROLFEEDBACK>"
   "MOVEMENTCONTROLFEEDBACK"
   "<MOVEMENTCONTROLGOAL>"
   "MOVEMENTCONTROLGOAL"
   "<MOVEMENTCONTROLRESULT>"
   "MOVEMENTCONTROLRESULT"
>>>>>>> 12be1fcab963b329af0649c4075d9d1835a9ee03
  ))

