; Auto-generated. Do not edit!


(cl:in-package tiago1-msg)


;//! \htmlinclude ArmControlGoal.msg.html

(cl:defclass <ArmControlGoal> (roslisp-msg-protocol:ros-message)
  ((degree
    :reader degree
    :initarg :degree
    :type cl:integer
    :initform 0))
)

(cl:defclass ArmControlGoal (<ArmControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago1-msg:<ArmControlGoal> is deprecated: use tiago1-msg:ArmControlGoal instead.")))

(cl:ensure-generic-function 'degree-val :lambda-list '(m))
(cl:defmethod degree-val ((m <ArmControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago1-msg:degree-val is deprecated.  Use tiago1-msg:degree instead.")
  (degree m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmControlGoal>) ostream)
  "Serializes a message object of type '<ArmControlGoal>"
  (cl:let* ((signed (cl:slot-value msg 'degree)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmControlGoal>) istream)
  "Deserializes a message object of type '<ArmControlGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'degree) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmControlGoal>)))
  "Returns string type for a message object of type '<ArmControlGoal>"
  "tiago1/ArmControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmControlGoal)))
  "Returns string type for a message object of type 'ArmControlGoal"
  "tiago1/ArmControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmControlGoal>)))
  "Returns md5sum for a message object of type '<ArmControlGoal>"
  "b4e0ba4860b4ebee3638b4876ab39423")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmControlGoal)))
  "Returns md5sum for a message object of type 'ArmControlGoal"
  "b4e0ba4860b4ebee3638b4876ab39423")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmControlGoal>)))
  "Returns full string definition for message of type '<ArmControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 degree~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmControlGoal)))
  "Returns full string definition for message of type 'ArmControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 degree~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmControlGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmControlGoal
    (cl:cons ':degree (degree msg))
))
