; Auto-generated. Do not edit!


(cl:in-package tiago1-msg)


;//! \htmlinclude ArmControlFeedback.msg.html

(cl:defclass <ArmControlFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass ArmControlFeedback (<ArmControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago1-msg:<ArmControlFeedback> is deprecated: use tiago1-msg:ArmControlFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <ArmControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago1-msg:status-val is deprecated.  Use tiago1-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmControlFeedback>) ostream)
  "Serializes a message object of type '<ArmControlFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmControlFeedback>) istream)
  "Deserializes a message object of type '<ArmControlFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmControlFeedback>)))
  "Returns string type for a message object of type '<ArmControlFeedback>"
  "tiago1/ArmControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmControlFeedback)))
  "Returns string type for a message object of type 'ArmControlFeedback"
  "tiago1/ArmControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmControlFeedback>)))
  "Returns md5sum for a message object of type '<ArmControlFeedback>"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmControlFeedback)))
  "Returns md5sum for a message object of type 'ArmControlFeedback"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmControlFeedback>)))
  "Returns full string definition for message of type '<ArmControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmControlFeedback)))
  "Returns full string definition for message of type 'ArmControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmControlFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmControlFeedback
    (cl:cons ':status (status msg))
))
