; Auto-generated. Do not edit!


(cl:in-package tiago1-msg)


;//! \htmlinclude GripperControlGoal.msg.html

(cl:defclass <GripperControlGoal> (roslisp-msg-protocol:ros-message)
  ((gripnogrip
    :reader gripnogrip
    :initarg :gripnogrip
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GripperControlGoal (<GripperControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago1-msg:<GripperControlGoal> is deprecated: use tiago1-msg:GripperControlGoal instead.")))

(cl:ensure-generic-function 'gripnogrip-val :lambda-list '(m))
(cl:defmethod gripnogrip-val ((m <GripperControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago1-msg:gripnogrip-val is deprecated.  Use tiago1-msg:gripnogrip instead.")
  (gripnogrip m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperControlGoal>) ostream)
  "Serializes a message object of type '<GripperControlGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'gripnogrip) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperControlGoal>) istream)
  "Deserializes a message object of type '<GripperControlGoal>"
    (cl:setf (cl:slot-value msg 'gripnogrip) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperControlGoal>)))
  "Returns string type for a message object of type '<GripperControlGoal>"
  "tiago1/GripperControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperControlGoal)))
  "Returns string type for a message object of type 'GripperControlGoal"
  "tiago1/GripperControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperControlGoal>)))
  "Returns md5sum for a message object of type '<GripperControlGoal>"
  "2cf3148cf31b5505879c305233af44a4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperControlGoal)))
  "Returns md5sum for a message object of type 'GripperControlGoal"
  "2cf3148cf31b5505879c305233af44a4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperControlGoal>)))
  "Returns full string definition for message of type '<GripperControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool gripnogrip~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperControlGoal)))
  "Returns full string definition for message of type 'GripperControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool gripnogrip~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperControlGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperControlGoal
    (cl:cons ':gripnogrip (gripnogrip msg))
))
