; Auto-generated. Do not edit!


(cl:in-package tiago1-msg)


;//! \htmlinclude GripperControlResult.msg.html

(cl:defclass <GripperControlResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GripperControlResult (<GripperControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago1-msg:<GripperControlResult> is deprecated: use tiago1-msg:GripperControlResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GripperControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago1-msg:success-val is deprecated.  Use tiago1-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperControlResult>) ostream)
  "Serializes a message object of type '<GripperControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperControlResult>) istream)
  "Deserializes a message object of type '<GripperControlResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperControlResult>)))
  "Returns string type for a message object of type '<GripperControlResult>"
  "tiago1/GripperControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperControlResult)))
  "Returns string type for a message object of type 'GripperControlResult"
  "tiago1/GripperControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperControlResult>)))
  "Returns md5sum for a message object of type '<GripperControlResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperControlResult)))
  "Returns md5sum for a message object of type 'GripperControlResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperControlResult>)))
  "Returns full string definition for message of type '<GripperControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperControlResult)))
  "Returns full string definition for message of type 'GripperControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperControlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperControlResult
    (cl:cons ':success (success msg))
))
