; Auto-generated. Do not edit!


(cl:in-package tiago1-msg)


;//! \htmlinclude MovementControlResult.msg.html

(cl:defclass <MovementControlResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MovementControlResult (<MovementControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovementControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovementControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago1-msg:<MovementControlResult> is deprecated: use tiago1-msg:MovementControlResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MovementControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago1-msg:success-val is deprecated.  Use tiago1-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovementControlResult>) ostream)
  "Serializes a message object of type '<MovementControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovementControlResult>) istream)
  "Deserializes a message object of type '<MovementControlResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovementControlResult>)))
  "Returns string type for a message object of type '<MovementControlResult>"
  "tiago1/MovementControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovementControlResult)))
  "Returns string type for a message object of type 'MovementControlResult"
  "tiago1/MovementControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovementControlResult>)))
  "Returns md5sum for a message object of type '<MovementControlResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovementControlResult)))
  "Returns md5sum for a message object of type 'MovementControlResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovementControlResult>)))
  "Returns full string definition for message of type '<MovementControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovementControlResult)))
  "Returns full string definition for message of type 'MovementControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovementControlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovementControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MovementControlResult
    (cl:cons ':success (success msg))
))
