
(cl:in-package :asdf)

(defsystem "tiago1-msg"
<<<<<<< HEAD
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "Voice_rec" :depends-on ("_package_Voice_rec"))
    (:file "_package_Voice_rec" :depends-on ("_package"))
=======
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :nav_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "ArmControlAction" :depends-on ("_package_ArmControlAction"))
    (:file "_package_ArmControlAction" :depends-on ("_package"))
    (:file "ArmControlActionFeedback" :depends-on ("_package_ArmControlActionFeedback"))
    (:file "_package_ArmControlActionFeedback" :depends-on ("_package"))
    (:file "ArmControlActionGoal" :depends-on ("_package_ArmControlActionGoal"))
    (:file "_package_ArmControlActionGoal" :depends-on ("_package"))
    (:file "ArmControlActionResult" :depends-on ("_package_ArmControlActionResult"))
    (:file "_package_ArmControlActionResult" :depends-on ("_package"))
    (:file "ArmControlFeedback" :depends-on ("_package_ArmControlFeedback"))
    (:file "_package_ArmControlFeedback" :depends-on ("_package"))
    (:file "ArmControlGoal" :depends-on ("_package_ArmControlGoal"))
    (:file "_package_ArmControlGoal" :depends-on ("_package"))
    (:file "ArmControlResult" :depends-on ("_package_ArmControlResult"))
    (:file "_package_ArmControlResult" :depends-on ("_package"))
    (:file "GripperControlAction" :depends-on ("_package_GripperControlAction"))
    (:file "_package_GripperControlAction" :depends-on ("_package"))
    (:file "GripperControlActionFeedback" :depends-on ("_package_GripperControlActionFeedback"))
    (:file "_package_GripperControlActionFeedback" :depends-on ("_package"))
    (:file "GripperControlActionGoal" :depends-on ("_package_GripperControlActionGoal"))
    (:file "_package_GripperControlActionGoal" :depends-on ("_package"))
    (:file "GripperControlActionResult" :depends-on ("_package_GripperControlActionResult"))
    (:file "_package_GripperControlActionResult" :depends-on ("_package"))
    (:file "GripperControlFeedback" :depends-on ("_package_GripperControlFeedback"))
    (:file "_package_GripperControlFeedback" :depends-on ("_package"))
    (:file "GripperControlGoal" :depends-on ("_package_GripperControlGoal"))
    (:file "_package_GripperControlGoal" :depends-on ("_package"))
    (:file "GripperControlResult" :depends-on ("_package_GripperControlResult"))
    (:file "_package_GripperControlResult" :depends-on ("_package"))
    (:file "MovementControlAction" :depends-on ("_package_MovementControlAction"))
    (:file "_package_MovementControlAction" :depends-on ("_package"))
    (:file "MovementControlActionFeedback" :depends-on ("_package_MovementControlActionFeedback"))
    (:file "_package_MovementControlActionFeedback" :depends-on ("_package"))
    (:file "MovementControlActionGoal" :depends-on ("_package_MovementControlActionGoal"))
    (:file "_package_MovementControlActionGoal" :depends-on ("_package"))
    (:file "MovementControlActionResult" :depends-on ("_package_MovementControlActionResult"))
    (:file "_package_MovementControlActionResult" :depends-on ("_package"))
    (:file "MovementControlFeedback" :depends-on ("_package_MovementControlFeedback"))
    (:file "_package_MovementControlFeedback" :depends-on ("_package"))
    (:file "MovementControlGoal" :depends-on ("_package_MovementControlGoal"))
    (:file "_package_MovementControlGoal" :depends-on ("_package"))
    (:file "MovementControlResult" :depends-on ("_package_MovementControlResult"))
    (:file "_package_MovementControlResult" :depends-on ("_package"))
>>>>>>> 12be1fcab963b329af0649c4075d9d1835a9ee03
  ))